export const characterBase = [{
        name: 'Eirika',
        startingLv: '1',
        class: 'Lord',
        hp: '16',
        str: '4',
        skl: '8',
        spd: '9',
        lck: '5',
        def: '3',
        res: '1',
        mov: '5',
        con: '5'
    },
    {
        name: 'Seth',
        startingLv: '1',
        class: 'Paladin',
        hp: '30',
        str: '14',
        skl: '13',
        spd: '12',
        lck: '13',
        def: '11',
        res: '8',
        mov: '8',
        con: '11'
    },
    {
        name: 'Franz',
        startingLv: '1',
        class: 'Cavalier',
        hp: '20',
        str: '7',
        skl: '5',
        spd: '7',
        lck: '2',
        def: '6',
        res: '1',
        mov: '7',
        con: '9'
    },
    {
        name: 'Gilliam',
        startingLv: '4',
        class: 'Knight',
        hp: '25',
        str: '9',
        skl: '6',
        spd: '3',
        lck: '3',
        def: '9',
        res: '3',
        mov: '4',
        con: '14'
    },
    {
        name: 'Vanessa',
        startingLv: '1',
        class: 'Pegasus Knight',
        hp: '17',
        str: '5',
        skl: '7',
        spd: '11',
        lck: '4',
        def: '6',
        res: '5',
        mov: '7',
        con: '5'
    },
    {
        name: 'Moulder',
        startingLv: '3',
        class: 'Priest',
        hp: '20',
        str: '4',
        skl: '6',
        spd: '9',
        lck: '1',
        def: '2',
        res: '5',
        mov: '5',
        con: '9'
    },
    {
        name: 'Ross',
        startingLv: '1',
        class: 'Journeyman',
        hp: '15',
        str: '5',
        skl: '2',
        spd: '3',
        lck: '8',
        def: '3',
        res: '0',
        mov: '4',
        con: '8'
    },
    {
        name: 'Garcia',
        startingLv: '4',
        class: 'Fighter',
        hp: '28',
        str: '8',
        skl: '7',
        spd: '7',
        lck: '3',
        def: '5',
        res: '1',
        mov: '5',
        con: '14'
    },
    {
        name: 'Neimi',
        startingLv: '1',
        class: 'Archer',
        hp: '17',
        str: '4',
        skl: '5',
        spd: '6',
        lck: '4',
        def: '3',
        res: '2',
        mov: '5',
        con: '5'
    },
    {
        name: 'Colm',
        startingLv: '2',
        class: 'Thief',
        hp: '18',
        str: '4',
        skl: '4',
        spd: '10',
        lck: '8',
        def: '3',
        res: '1',
        mov: '6',
        con: '6'
    },
    {
        name: 'Artur',
        startingLv: '2',
        class: 'Monk',
        hp: '19',
        str: '6',
        skl: '6',
        spd: '8',
        lck: '2',
        def: '2',
        res: '6',
        mov: '5',
        con: '6'
    },
    {
        name: 'Lute',
        startingLv: '1',
        class: 'Mage',
        hp: '17',
        str: '6',
        skl: '6',
        spd: '7',
        lck: '8',
        def: '3',
        res: '5',
        mov: '5',
        con: '3'
    },
    {
        name: 'Natasha',
        startingLv: '1',
        class: 'Cleric',
        hp: '18',
        str: '2',
        skl: '4',
        spd: '8',
        lck: '6',
        def: '2',
        res: '6',
        mov: '5',
        con: '4'
    },
    {
        name: 'Joshua',
        startingLv: '5',
        class: 'Myrmidon',
        hp: '24',
        str: '8',
        skl: '13',
        spd: '14',
        lck: '7',
        def: '5',
        res: '2',
        mov: '5',
        con: '8'
    },
    {
        name: 'Ephraim',
        startingLv: '4',
        class: 'Lord',
        hp: '23',
        str: '8',
        skl: '9',
        spd: '11',
        lck: '8',
        def: '7',
        res: '2',
        mov: '5',
        con: '8'
    },
    {
        name: 'Forde',
        startingLv: '6',
        class: 'Cavalier',
        hp: '24',
        str: '7',
        skl: '8',
        spd: '8',
        lck: '7',
        def: '8',
        res: '2',
        mov: '7',
        con: '9'
    },
    {
        name: 'Kyle',
        startingLv: '5',
        class: 'Cavalier',
        hp: '25',
        str: '9',
        skl: '6',
        spd: '7',
        lck: '6',
        def: '9',
        res: '1',
        mov: '7',
        con: '10'
    },
    {
        name: 'Orson',
        startingLv: '3',
        class: 'Paladin',
        hp: '34',
        str: '15',
        skl: '13',
        spd: '11',
        lck: '4',
        def: '13',
        res: '7',
        mov: '8',
        con: '12'
    },
    {
        name: 'Tana',
        startingLv: '4',
        class: 'Pegasus Knight',
        hp: '20',
        str: '7',
        skl: '9',
        spd: '13',
        lck: '8',
        def: '6',
        res: '7',
        mov: '7',
        con: '5'
    },
    {
        name: 'Amelia',
        startingLv: '1',
        class: 'Recruit',
        hp: '16',
        str: '4',
        skl: '3',
        spd: '4',
        lck: '6',
        def: '2',
        res: '3',
        mov: '4',
        con: '6'
    },
    {
        name: 'Innes',
        startingLv: '1',
        class: 'Sniper',
        hp: '31',
        str: '14',
        skl: '13',
        spd: '15',
        lck: '14',
        def: '10',
        res: '9',
        mov: '6',
        con: '9'
    },
    {
        name: 'Gerik',
        startingLv: '10',
        class: 'Mercenary',
        hp: '32',
        str: '14',
        skl: '13',
        spd: '13',
        lck: '8',
        def: '10',
        res: '4',
        mov: '5',
        con: '13'
    },
    {
        name: 'Tethys',
        startingLv: '1',
        class: 'Dancer',
        hp: '18',
        str: '1',
        skl: '2',
        spd: '12',
        lck: '10',
        def: '5',
        res: '4',
        mov: '5',
        con: '5'
    },
    {
        name: 'Marisa',
        startingLv: '5',
        class: 'Myrmidon',
        hp: '23',
        str: '7',
        skl: '12',
        spd: '13',
        lck: '9',
        def: '4',
        res: '3',
        mov: '5',
        con: '5'
    },
    {
        name: 'L’Arachel',
        startingLv: '3',
        class: 'Troubadour',
        hp: '18',
        str: '6',
        skl: '6',
        spd: '10',
        lck: '12',
        def: '5',
        res: '8',
        mov: '6',
        con: '5'
    },
    {
        name: 'Dozla',
        startingLv: '1',
        class: 'Berserker',
        hp: '43',
        str: '16',
        skl: '11',
        spd: '9',
        lck: '4',
        def: '11',
        res: '6',
        mov: '6',
        con: '16'
    },
    {
        name: 'Saleh',
        startingLv: '1',
        class: 'Sage',
        hp: '30',
        str: '16',
        skl: '18',
        spd: '14',
        lck: '11',
        def: '8',
        res: '13',
        mov: '6',
        con: '8'
    },
    {
        name: 'Ewan',
        startingLv: '1',
        class: 'Pupil',
        hp: '15',
        str: '3',
        skl: '2',
        spd: '5',
        lck: '5',
        def: '0',
        res: '3',
        mov: '4',
        con: '5'
    },
    {
        name: 'Cormag',
        startingLv: '9',
        class: 'Wyvern Rider',
        hp: '30',
        str: '14',
        skl: '9',
        spd: '10',
        lck: '4',
        def: '12',
        res: '2',
        mov: '7',
        con: '11'
    },
    {
        name: 'Rennac',
        startingLv: '1',
        class: 'Rogue',
        hp: '28',
        str: '10',
        skl: '16',
        spd: '17',
        lck: '5',
        def: '9',
        res: '11',
        mov: '6',
        con: '7'
    },
    {
        name: 'Duessel',
        startingLv: '8',
        class: 'Great Knight',
        hp: '41',
        str: '17',
        skl: '12',
        spd: '12',
        lck: '8',
        def: '17',
        res: '9',
        mov: '6',
        con: '15'
    },
    {
        name: 'Knoll',
        startingLv: '10',
        class: 'Shaman',
        hp: '22',
        str: '13',
        skl: '9',
        spd: '8',
        lck: '0',
        def: '2',
        res: '10',
        mov: '5',
        con: '7'
    },
    {
        name: 'Myrrh',
        startingLv: '1',
        class: 'Manakete',
        hp: '15',
        str: '3',
        skl: '1',
        spd: '5',
        lck: '3',
        def: '2',
        res: '7',
        mov: '6',
        con: '5'
    },
    {
        name: 'Syrene',
        startingLv: '1',
        class: 'Falcoknight',
        hp: '27',
        str: '12',
        skl: '13',
        spd: '15',
        lck: '12',
        def: '10',
        res: '12',
        mov: '8',
        con: '7'
    }
]


export const characterGrowths = [{
        name: 'Name',
        hp: 'HP',
        atk: 'S/M',
        skl: 'Skl',
        spd: 'Spd',
        lck: 'Lck',
        def: 'Def',
        res: 'Res'
    },
    {
        name: 'Eirika',
        hp: '70',
        atk: '40',
        skl: '60',
        spd: '60',
        lck: '60',
        def: '30',
        res: '30'
    },
    {
        name: 'Seth',
        hp: '90',
        atk: '50',
        skl: '45',
        spd: '45',
        lck: '25',
        def: '40',
        res: '30'
    },
    {
        name: 'Franz',
        hp: '80',
        atk: '40',
        skl: '40',
        spd: '50',
        lck: '40',
        def: '25',
        res: '20'
    },
    {
        name: 'Gilliam',
        hp: '90',
        atk: '45',
        skl: '35',
        spd: '30',
        lck: '30',
        def: '55',
        res: '20'
    },
    {
        name: 'Moulder',
        hp: '70',
        atk: '40',
        skl: '50',
        spd: '40',
        lck: '20',
        def: '25',
        res: '25'
    },
    {
        name: 'Vanessa',
        hp: '50',
        atk: '35',
        skl: '55',
        spd: '60',
        lck: '50',
        def: '20',
        res: '30'
    },
    {
        name: 'Ross',
        hp: '70',
        atk: '50',
        skl: '35',
        spd: '30',
        lck: '40',
        def: '25',
        res: '20'
    },
    {
        name: 'Garcia',
        hp: '80',
        atk: '65',
        skl: '40',
        spd: '20',
        lck: '40',
        def: '25',
        res: '15'
    },
    {
        name: 'Neimi',
        hp: '55',
        atk: '45',
        skl: '50',
        spd: '60',
        lck: '50',
        def: '15',
        res: '35'
    },
    {
        name: 'Colm',
        hp: '75',
        atk: '40',
        skl: '40',
        spd: '65',
        lck: '45',
        def: '25',
        res: '20'
    },
    {
        name: 'Artur',
        hp: '55',
        atk: '50',
        skl: '50',
        spd: '40',
        lck: '25',
        def: '15',
        res: '55'
    },
    {
        name: 'Lute',
        hp: '45',
        atk: '65',
        skl: '30',
        spd: '45',
        lck: '45',
        def: '15',
        res: '40'
    },
    {
        name: 'Natasha',
        hp: '50',
        atk: '60',
        skl: '25',
        spd: '40',
        lck: '60',
        def: '15',
        res: '55'
    },
    {
        name: 'Joshua',
        hp: '80',
        atk: '35',
        skl: '55',
        spd: '55',
        lck: '30',
        def: '20',
        res: '20'
    },
    {
        name: 'Ephraim',
        hp: '80',
        atk: '55',
        skl: '55',
        spd: '45',
        lck: '50',
        def: '35',
        res: '25'
    },
    {
        name: 'Forde',
        hp: '85',
        atk: '40',
        skl: '50',
        spd: '45',
        lck: '35',
        def: '20',
        res: '25'
    },
    {
        name: 'Kyle',
        hp: '90',
        atk: '50',
        skl: '40',
        spd: '40',
        lck: '20',
        def: '25',
        res: '20'
    },
    {
        name: 'Tana',
        hp: '65',
        atk: '45',
        skl: '40',
        spd: '65',
        lck: '60',
        def: '20',
        res: '25'
    },
    {
        name: 'Amelia',
        hp: '60',
        atk: '35',
        skl: '40',
        spd: '40',
        lck: '50',
        def: '30',
        res: '15'
    },
    {
        name: 'Innes',
        hp: '75',
        atk: '40',
        skl: '40',
        spd: '45',
        lck: '45',
        def: '20',
        res: '25'
    },
    {
        name: 'Character',
        hp: 'HP',
        atk: 'S/M ',
        skl: 'Skl',
        spd: 'Spd',
        lck: 'Lck',
        def: 'Def',
        res: 'Res'
    },
    {
        name: 'Gerik',
        hp: '90',
        atk: '45',
        skl: '40',
        spd: '30',
        lck: '30',
        def: '35',
        res: '25'
    },
    {
        name: 'Tethys',
        hp: '85',
        atk: '5',
        skl: '10',
        spd: '70',
        lck: '80',
        def: '30',
        res: '75'
    },
    {
        name: 'Marisa',
        hp: '75',
        atk: '30',
        skl: '55',
        spd: '60',
        lck: '50',
        def: '15',
        res: '25'
    },
    {
        name: 'L’Arachel',
        hp: '45',
        atk: '50',
        skl: '45',
        spd: '45',
        lck: '65',
        def: '15',
        res: '50'
    },
    {
        name: 'Dozla',
        hp: '85',
        atk: '50',
        skl: '35',
        spd: '40',
        lck: '30',
        def: '30',
        res: '25'
    },
    {
        name: 'Saleh',
        hp: '50',
        atk: '30',
        skl: '25',
        spd: '40',
        lck: '40',
        def: '30',
        res: '35'
    },
    {
        name: 'Ewan',
        hp: '50',
        atk: '45',
        skl: '40',
        spd: '35',
        lck: '50',
        def: '15',
        res: '40'
    },
    {
        name: 'Cormag',
        hp: '85',
        atk: '55',
        skl: '40',
        spd: '45',
        lck: '35',
        def: '25',
        res: '15'
    },
    {
        name: 'Rennac',
        hp: '65',
        atk: '25',
        skl: '45',
        spd: '60',
        lck: '25',
        def: '25',
        res: '30'
    },
    {
        name: 'Duessel',
        hp: '85',
        atk: '55',
        skl: '40',
        spd: '30',
        lck: '20',
        def: '45',
        res: '30'
    },
    {
        name: 'Knoll',
        hp: '70',
        atk: '50',
        skl: '40',
        spd: '35',
        lck: '20',
        def: '10',
        res: '45'
    },
    {
        name: 'Myrrh',
        hp: '130',
        atk: '90',
        skl: '85',
        spd: '65',
        lck: '30',
        def: '150',
        res: '30'
    },
    {
        name: 'Syrene',
        hp: '70',
        atk: '40',
        skl: '50',
        spd: '60',
        lck: '30',
        def: '20',
        res: '50'
    },
    {
        name: 'Caellach',
        hp: '85',
        atk: '50',
        skl: '45',
        spd: '45',
        lck: '20',
        def: '30',
        res: '20'
    },
    {
        name: 'Orson',
        hp: '80',
        atk: '55',
        skl: '45',
        spd: '40',
        lck: '25',
        def: '45',
        res: '30'
    },
    {
        name: 'Riev',
        hp: '75',
        atk: '45',
        skl: '50',
        spd: '40',
        lck: '15',
        def: '20',
        res: '45'
    },
    {
        name: 'Ismaire',
        hp: '75',
        atk: '30',
        skl: '60',
        spd: '55',
        lck: '30',
        def: '20',
        res: '25'
    },
    {
        name: 'Selena',
        hp: '85',
        atk: '40',
        skl: '55',
        spd: '40',
        lck: '25',
        def: '20',
        res: '30'
    },
    {
        name: 'Glen',
        hp: '85',
        atk: '45',
        skl: '50',
        spd: '45',
        lck: '20',
        def: '35',
        res: '40'
    },
    {
        name: 'Hayden',
        hp: '70',
        atk: '40',
        skl: '45',
        spd: '45',
        lck: '40',
        def: '25',
        res: '25'
    },
    {
        name: 'Valter',
        hp: '80',
        atk: '40',
        skl: '55',
        spd: '50',
        lck: '15',
        def: '20',
        res: '20'
    },
    {
        name: 'Fado',
        hp: '85',
        atk: '55',
        skl: '40',
        spd: '30',
        lck: '25',
        def: '45',
        res: '25'
    },
    {
        name: 'Lyon',
        hp: '85',
        atk: '50',
        skl: '55',
        spd: '55',
        lck: '30',
        def: '45',
        res: '55'
    },
    {
        name: 'Knoll Phantom',
        hp: '0',
        atk: '50',
        skl: '50',
        spd: '40',
        lck: '55',
        def: '0',
        res: '0'
    },
    {
        name: 'Ewan Phantom',
        hp: '0',
        atk: '70',
        skl: '40',
        spd: '20',
        lck: '40',
        def: '0',
        res: '0'
    },
    {
        name: 'Lyon Phantom',
        hp: '0',
        atk: '60',
        skl: '45',
        spd: '30',
        lck: '60',
        def: '0',
        res: '0'
    }
]


export const characterMax = [
    
    {
        class: 'Great Lord (Ephraim)',
        hp: '60',
        atk: '27',
        skl: '26',
        spd: '24',
        lck: '30',
        def: '23',
        res: '23',
        mov: '15',
        con: '25'
    },
    {
        class: 'Great Lord (Eirika)',
        hp: '60',
        atk: '24',
        skl: '29',
        spd: '30',
        lck: '30',
        def: '22',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'Dancer',
        hp: '60',
        atk: '10',
        skl: '10',
        spd: '30',
        lck: '30',
        def: '24',
        res: '26',
        mov: '15',
        con: '20'
    },
    {
        class: 'Paladin (M)',
        hp: '60',
        atk: '25',
        skl: '26',
        spd: '24',
        lck: '30',
        def: '25',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'Paladin (F)',
        hp: '60',
        atk: '23',
        skl: '27',
        spd: '25',
        lck: '30',
        def: '24',
        res: '26',
        mov: '15',
        con: '25'
    },
    {
        class: 'Great Knight (M)',
        hp: '60',
        atk: '28',
        skl: '24',
        spd: '24',
        lck: '30',
        def: '29',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'Great Knight (F)',
        hp: '60',
        atk: '26',
        skl: '26',
        spd: '25',
        lck: '30',
        def: '28',
        res: '26',
        mov: '15',
        con: '25'
    },
    {
        class: 'General (M)',
        hp: '60',
        atk: '29',
        skl: '27',
        spd: '24',
        lck: '30',
        def: '30',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'General (F)',
        hp: '60',
        atk: '27',
        skl: '28',
        spd: '25',
        lck: '30',
        def: '29',
        res: '26',
        mov: '15',
        con: '25'
    },
    {
        class: 'Hero (M)',
        hp: '60',
        atk: '25',
        skl: '30',
        spd: '26',
        lck: '30',
        def: '25',
        res: '22',
        mov: '15',
        con: '25'
    },
    {
        class: 'Hero (F)',
        hp: '60',
        atk: '24',
        skl: '30',
        spd: '26',
        lck: '30',
        def: '24',
        res: '24',
        mov: '15',
        con: '25'
    },
    {
        class: 'Swordmaster (M)',
        hp: '60',
        atk: '24',
        skl: '29',
        spd: '30',
        lck: '30',
        def: '22',
        res: '23',
        mov: '15',
        con: '20'
    },
    {
        class: 'Swordmaster (F)',
        hp: '60',
        atk: '22',
        skl: '29',
        spd: '30',
        lck: '30',
        def: '22',
        res: '25',
        mov: '15',
        con: '20'
    },
    {
        class: 'Assassin (M)',
        hp: '60',
        atk: '20',
        skl: '30',
        spd: '30',
        lck: '30',
        def: '20',
        res: '20',
        mov: '15',
        con: '20'
    },
    {
        class: 'Assassin (F)',
        hp: '60',
        atk: '20',
        skl: '30',
        spd: '30',
        lck: '30',
        def: '20',
        res: '20',
        mov: '15',
        con: '20'
    },
    {
        class: 'Rogue',
        hp: '60',
        atk: '20',
        skl: '30',
        spd: '30',
        lck: '30',
        def: '20',
        res: '20',
        mov: '15',
        con: '20'
    },
    {
        class: 'Sniper (M)',
        hp: '60',
        atk: '25',
        skl: '30',
        spd: '28',
        lck: '30',
        def: '25',
        res: '23',
        mov: '15',
        con: '20'
    },
    {
        class: 'Sniper (F)',
        hp: '60',
        atk: '24',
        skl: '30',
        spd: '29',
        lck: '30',
        def: '24',
        res: '24',
        mov: '15',
        con: '20'
    },
    {
        class: 'Ranger (M)',
        hp: '60',
        atk: '25',
        skl: '28',
        spd: '30',
        lck: '30',
        def: '24',
        res: '23',
        mov: '15',
        con: '25'
    },
    {
        class: 'Ranger (F)',
        hp: '60',
        atk: '23',
        skl: '28',
        spd: '30',
        lck: '30',
        def: '22',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'Wyvern Lord (M)',
        hp: '60',
        atk: '27',
        skl: '25',
        spd: '23',
        lck: '30',
        def: '28',
        res: '22',
        mov: '15',
        con: '25'
    },
    {
        class: 'Wyvern Lord (F)',
        hp: '60',
        atk: '25',
        skl: '26',
        spd: '24',
        lck: '30',
        def: '27',
        res: '23',
        mov: '15',
        con: '25'
    },
    {
        class: 'Wyvern Knight (M)',
        hp: '60',
        atk: '25',
        skl: '26',
        spd: '28',
        lck: '30',
        def: '24',
        res: '22',
        mov: '15',
        con: '25'
    },
    {
        class: 'Wyvern Knight (F)',
        hp: '60',
        atk: '24',
        skl: '27',
        spd: '29',
        lck: '30',
        def: '23',
        res: '23',
        mov: '15',
        con: '25'
    },
    {
        class: 'Sage (M)',
        hp: '60',
        atk: '28',
        skl: '30',
        spd: '26',
        lck: '30',
        def: '21',
        res: '25',
        mov: '15',
        con: '20'
    },
    {
        class: 'Sage (F)',
        hp: '60',
        atk: '30',
        skl: '28',
        spd: '26',
        lck: '30',
        def: '21',
        res: '25',
        mov: '15',
        con: '20'
    },
    {
        class: 'Mage Knight (M)',
        hp: '60',
        atk: '24',
        skl: '26',
        spd: '25',
        lck: '30',
        def: '24',
        res: '25',
        mov: '15',
        con: '25'
    },
    {
        class: 'Mage Knight (F)',
        hp: '60',
        atk: '25',
        skl: '24',
        spd: '25',
        lck: '30',
        def: '24',
        res: '28',
        mov: '15',
        con: '25'
    },
    {
        class: 'Bishop (M)',
        hp: '60',
        atk: '25',
        skl: '26',
        spd: '24',
        lck: '30',
        def: '22',
        res: '30',
        mov: '15',
        con: '20'
    },
    {
        class: 'Bishop (F)',
        hp: '60',
        atk: '25',
        skl: '25',
        spd: '26',
        lck: '30',
        def: '21',
        res: '30',
        mov: '15',
        con: '20'
    },
    {
        class: 'Druid (M)',
        hp: '60',
        atk: '29',
        skl: '26',
        spd: '26',
        lck: '30',
        def: '21',
        res: '28',
        mov: '15',
        con: '20'
    },
    {
        class: 'Druid (F)',
        hp: '60',
        atk: '29',
        skl: '26',
        spd: '26',
        lck: '30',
        def: '20',
        res: '29',
        mov: '15',
        con: '20'
    },
    {
        class: 'Summoner (M)',
        hp: '60',
        atk: '27',
        skl: '27',
        spd: '26',
        lck: '30',
        def: '20',
        res: '28',
        mov: '15',
        con: '20'
    },
    {
        class: 'Summoner (F)',
        hp: '60',
        atk: '27',
        skl: '27',
        spd: '26',
        lck: '30',
        def: '20',
        res: '28',
        mov: '15',
        con: '20'
    },
    {
        class: 'Journeyman (3)',
        hp: '60',
        atk: '26',
        skl: '29',
        spd: '28',
        lck: '30',
        def: '23',
        res: '23',
        mov: '15',
        con: '20'
    },
    {
        class: 'Recruit (3)',
        hp: '60',
        atk: '23',
        skl: '30',
        spd: '29',
        lck: '30',
        def: '22',
        res: '26',
        mov: '15',
        con: '20'
    },
    {
        class: 'Pupil (3)',
        hp: '60',
        atk: '29',
        skl: '28',
        spd: '27',
        lck: '30',
        def: '21',
        res: '26',
        mov: '15',
        con: '20'
    },
    {
        class: 'Manakete (M)',
        hp: '60',
        atk: '20',
        skl: '20',
        spd: '20',
        lck: '30',
        def: '20',
        res: '20',
        mov: '15',
        con: '25'
    },
    {
        class: 'Manakete (F)',
        hp: '60',
        atk: '20',
        skl: '20',
        spd: '20',
        lck: '30',
        def: '20',
        res: '20',
        mov: '15',
        con: '20'
    },
    {
        class: 'Warrior',
        hp: '60',
        atk: '30',
        skl: '28',
        spd: '26',
        lck: '30',
        def: '26',
        res: '22',
        mov: '15',
        con: '25'
    },
    {
        class: 'Berserker',
        hp: '60',
        atk: '30',
        skl: '29',
        spd: '28',
        lck: '30',
        def: '23',
        res: '21',
        mov: '15',
        con: '25'
    },
    {
        class: 'Falcoknight',
        hp: '60',
        atk: '23',
        skl: '25',
        spd: '28',
        lck: '30',
        def: '23',
        res: '26',
        mov: '15',
        con: '25'
    },
    {
        class: 'Valkyrie',
        hp: '60',
        atk: '25',
        skl: '24',
        spd: '25',
        lck: '30',
        def: '24',
        res: '28',
        mov: '15',
        con: '25'
    },
    {
        class: 'Necromancer',
        hp: '60',
        atk: '30',
        skl: '25',
        spd: '25',
        lck: '30',
        def: '30',
        res: '30',
        mov: '15',
        con: '25'
    }

]


